### ISSUE TITLE
Update Space Page

### ISSUE THREAD

**Issue by duttakapil** [coderplex/coderplex#162]
We need to update our [/space](https://coderplex.org/space) page with some details. 

- [x] Remove the pricing section
- [x] Mention that the space is free to enter, no fee
- [x] Add Location : Swecha, Gachibowli 
- [x] Embed google Map with address https://www.google.co.in/maps/place/Swecha+Office/@17.4080245,78.3856767

**Comment by rkaranam** [comment]
Kapil, I will take this. Can someone guide me?

**Comment by M-ZubairAhmed** [comment]
Let me know what you need @Raja
Best Regards
Md Zubair Ahmed
Web & Mobile Developer

On 1 Feb 2018 10:35 pm, "Raja Sekhar Karanam" <notifications@github.com>
wrote:

Kapil, I will take this. Can someone guide me?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/coderplex/coderplex/issues/162#issuecomment-362333516>,
or mute the thread
