### ISSUE TITLE
Google Analytics?

### ISSUE THREAD

**Issue by harishkotra** [coderplex/coderplex#52]
Why is the site missing Google Analytics? I am sure it's been up for a while now. Please add GA guys :) @duttakapil @M-ZubairAhmed

**Comment by vinaypuppal** [comment]
Hi, I already added it at proxy server level that's why you did not notice in client side code. So server side Google analytics is enabled, benefit of this we can track track every user even if they have adblockers installed which usually blocks good analytics.

@duttakapil I just invited you to analytics dashboard, check your email.

**Comment by duttakapil** [comment]
I was about to mention this in our plan of action for v2. Good work @vinaypuppal, you are 2 steps ahead than everyone else :D

**Comment by harishkotra** [comment]
@vinaypuppal great. However, Adblock doesn't block Google Analytics.

**Comment by vinaypuppal** [comment]
@harishkotra I don't know about **Adblock** extension but other adblockers like **uBlock Origin** do block google analytics. I am just experimenting with server side analytics which i found recently More Info here: https://medium.freecodecamp.org/save-your-analytics-from-content-blockers-7ee08c6ec7ee

**Comment by duttakapil** [comment]
I just checked, and all ad blockers can block Analytics if they want to, but only some do by default. uBlock Origin is one of them, and I personally use that and recommend it to others as well.
