### ISSUE TITLE
Page after 'learn/subject'

### ISSUE THREAD

**Issue by M-ZubairAhmed** [coderplex/coderplex#66]
Let's have a discussion here so how the page looks like after user have selected a topic from `learn/subject`

**Comment by M-ZubairAhmed** [comment]
>The way we have thought initially was to run another page after user clicks on a particular topic on `learn/subject`.

So idea behind the next page is to have
- a two plane , left being scroll view of the complete curriculum  topics and left the topic content
- right plane could have useful links , best recommendations, YouTube video iframe (if available), our own high quality content (video or articles ) etc 
- design is still not finalized as we would like to have everyone opinion on it.

#### previously on this conversation
- @pbteja1998
- @duttakapil

**Comment by pbteja1998** [comment]
How about a Modal Popup in mobile view when user clicks on a topic.

**Comment by harishkotra** [comment]
The most intuitive way and also the most commonly used design pattern is what you mentioned Zubair. Also, having separate pages is an asset for good SEO and well.

**Comment by M-ZubairAhmed** [comment]
hmm, @pbteja1998 wouldn't a modal be a not so good UX?
@harishkotra do you have any improvements on that pattern you would like to suggest on

**Comment by pbteja1998** [comment]
We can go with the same design as https://www.howtographql.com/  

## Learn Page - Normal View
![learn](https://user-images.githubusercontent.com/17903466/32376925-316e88de-c0cc-11e7-93ae-59fe1b3654cd.png)

## Learn Page - Mobile View
![learn-mobile](https://user-images.githubusercontent.com/17903466/32376927-31a119b6-c0cc-11e7-8eb8-18504e2bcf6a.png)

## Learn/Subject Page - Normal View
![learn-subject](https://user-images.githubusercontent.com/17903466/32376929-31d23406-c0cc-11e7-9989-bcfe8d0004e5.png)

## Learn/Subject Page - Mobile View (with a sidebar that can be hidden)
![learn-subject-mobile](https://user-images.githubusercontent.com/17903466/32376930-31fc5970-c0cc-11e7-8735-31334a070e55.png)

**Comment by duttakapil** [comment]
@pbteja1998 this looks nice, we should take this up as inspiration for our design. 

The main problem we need to address with our learn guide interface is, atm we do not have much content per unit to display on the page. We only have a few concepts, one hyperlink to a video resource and one for a text resource recommendation per concept, and a few tasks to practice those concepts. The traditional left-hand / right-hand interface will end up making the page look empty. 

One solution to this that we have internally discussed was, we can scrape the resources and display them on the page. So we would try to scrape the video and the text content per concept, and display them on the right hand interface when the user opens up a particular unit. This would fill up the page. 

Question then is, to what extent can we scrape? What is the legality of that process? 

And also keeping in mind that this would be a temporary fix, because where we eventually want to get is building a learning platform where any one can create learning modules for different topics, anyone can edit them, make changes and send changes back. Anyone can also pull different modules together to create their own custom guides. In this version, we expect users to produce content (Videos on YouTube / Text on our site, saved on our servers). We wouldn't then need to scrape anything, we will use the YouTube API to display the videos and pull the content from our servers. 

So which way to go forward? Only based on that will we be able to make decisions on our design

**Comment by bhansa** [comment]
### About sidebar
What I think that the sidebar should be on the left side, most websites follow the same pattern.  

Most users follow the [F-shaped reading pattern](https://www.nngroup.com/articles/f-shaped-pattern-reading-web-content/), so there is less chance user goes to right side of the page to interact.

Websites like coursera, djangogirls tutorial, python docs follow the same. This is my personal opinion for sidebars as we are discussing.

**Comment by duttakapil** [comment]
What are Coursera's two sidebar's for?

**Comment by M-ZubairAhmed** [comment]
I was wondering what could be a better route for this page `learn/laravel/XXX`?

**Comment by pbteja1998** [comment]
If we are going to have this page, this page anyways contains different sections as sidebar, then we can remove `/learn/laravel` page and add that route to this page.

**Comment by saiabhijitht** [comment]
![learn layout7](https://user-images.githubusercontent.com/23223985/33146973-2d3ed4ba-cfec-11e7-9901-9533e25f85e9.jpg)
@M-ZubairAhmed @duttakapil

**Comment by duttakapil** [comment]
Let's not overuse the blue / purple color theme now @saiabhijitht. I feel the purple doesn't go along with the "Mark Completed" button.

**Comment by M-ZubairAhmed** [comment]
Lets finalize if we all agree on this? we have to start working on this soon

**Comment by saiabhijitht** [comment]
![learn](https://user-images.githubusercontent.com/23223985/33287183-e4a6f5de-d3dd-11e7-9dce-44a0f44dc156.jpg)
@M-ZubairAhmed

**Comment by saiabhijitht** [comment]
![learn layout10](https://user-images.githubusercontent.com/23223985/33314504-d3cd67cc-d453-11e7-88df-a2361d2545c1.jpg)
@M-ZubairAhmed @duttakapil

**Comment by saiabhijitht** [comment]
<img width="961" alt="learn cards11" src="https://user-images.githubusercontent.com/23223985/33316315-910df7c0-d459-11e7-849b-82faf8e2edba.png">
@M-ZubairAhmed Follow this Mockup for Learn page. For the next version, we shall plan to have a good image in banner and for each card.

**Comment by M-ZubairAhmed** [comment]
@saiabhijitht subject page can be finalized?

**Comment by saiabhijitht** [comment]
@M-ZubairAhmed Yes, from my side. @duttakapil  If there are there any issues from functional aspects in that page, any features are missing kind of things, please tell us. Then it could be finalized.

**Comment by M-ZubairAhmed** [comment]
@duttakapil if you have any feedback please feel free to reopen
